name: First Interaction

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: >
            Hello there 👋 This seems to be your first issue, thanks for your interest in contributing to Turbo!
            Make sure you've read our [contributing guidelines](https://github.com/teamcodebyte/turbo/blob/main/CONTRIBUTING.md)
            and also our [code of conduct](https://github.com/teamcodebyte/turbo/blob/main/CODE_OF_CONDUCT.md)
          pr-message: >
            Hello there 👋 This seems to be your first PR! Thanks for contributing to Turbo, we're really excited to have you!
            Just a friendly reminder to read our [contributing guidelines](https://github.com/teamcodebyte/turbo/blob/main/CONTRIBUTING.md) 
            and also our [code of conduct](https://github.com/teamcodebyte/turbo/blob/main/CODE_OF_CONDUCT.md)
